# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/newrecord.ui'
#
# Created: Thu Nov 24 15:01:27 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

import gettext
__trans = gettext.translation('ehr', fallback=True)
i18n = __trans.ugettext
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(863, 792)
        MainWindow.setWindowTitle(i18n("MainWindow"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 861, 261))
        self.groupBox.setTitle(i18n("Kişisel Bilgiler"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label.setText(i18n("Ad:"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.label_2.setText(i18n("Soyad:"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 101, 20))
        self.label_3.setText(i18n("Doğum Tarihi:"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 101, 20))
        self.label_4.setText(i18n("Cinsiyet:"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 111, 20))
        self.label_5.setText(i18n("Sigara Kullanımı:"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 200, 101, 20))
        self.label_6.setText(i18n("İçki Kullanımı:"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(160, 121, 151, 23))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(0, i18n("Seçiniz..."))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(1, i18n("Erkek"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(2, i18n("Kadın"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(160, 40, 151, 22))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 60, 151, 22))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 181, 101, 20))
        self.label_7.setText(i18n("SGK No:"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 101, 20))
        self.label_8.setText(i18n("Meslek:"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 161, 151, 23))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(0, i18n("Serbest Meslek"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(1, i18n("Mühendis"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(2, i18n("Doktor"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(3, i18n("Öğretim Görevlisi"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(4, i18n("Öğrenci"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(5, i18n("Diğer"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(6, i18n("Çalışmıyor"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 181, 151, 22))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 221, 151, 23))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(0, i18n("Kullanmıyor"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(1, i18n("Sosyal İçici"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(2, i18n("Günde < 5"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(3, i18n("0.5 Paket/Gün"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(4, i18n("1 Paket/Gün"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(5, i18n("1.5 Paket/Gün"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(6, i18n("2 Paket/Gün"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(7, i18n("> 2 Paket/Gün"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(160, 201, 151, 23))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.setItemText(0, i18n("Kullanmıyor"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.setItemText(1, i18n("Sosyal İçici"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.setItemText(2, i18n("1 Kadeh/Gün"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.setItemText(3, i18n("> 1 Kadeh/Gün"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(460, 134, 181, 22))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(340, 44, 101, 16))
        self.label_11.setText(i18n("Adres:"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(340, 114, 101, 16))
        self.label_12.setText(i18n("Telefon:"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(340, 134, 101, 16))
        self.label_15.setText(i18n("E-Posta:"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.textEdit = QtGui.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(460, 44, 181, 71))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(460, 114, 181, 22))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(680, 190, 171, 41))
        self.pushButton.setText(i18n("Fotoğraf Ekle"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/list-resource-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(680, 40, 171, 151))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(22, 0, 131, 131))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/meeting-organizer.png")))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.comboBox_5 = QtGui.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(160, 141, 151, 23))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.setItemText(0, i18n("Seçiniz..."))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.setItemText(1, i18n("Evli"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.setItemText(2, i18n("Bekar"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 140, 101, 20))
        self.label_10.setText(i18n("Medeni Durum:"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.dateEdit_2 = QtGui.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(160, 101, 151, 22))
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 80, 151, 22))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_13.setText(i18n("Doğum Yeri:"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 270, 861, 471))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabDiseases = QtGui.QWidget()
        self.tabDiseases.setObjectName(_fromUtf8("tabDiseases"))
        self.tabWidget.addTab(self.tabDiseases, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(690, 750, 167, 25))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(100, 750, 101, 22))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(7, 753, 110, 16))
        self.label_14.setText(i18n("İlk Vizit Tarihi:"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

