# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/newrecord.ui'
#
# Created: Thu Nov 24 16:19:31 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

import gettext
__trans = gettext.translation('ehr', fallback=True)
i18n = __trans.ugettext
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NewRecordWindow(object):
    def setupUi(self, NewRecordWindow):
        NewRecordWindow.setObjectName(_fromUtf8("NewRecordWindow"))
        NewRecordWindow.resize(992, 754)
        NewRecordWindow.setWindowTitle(i18n("Yeni Hasta Kaydı"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Health.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewRecordWindow.setWindowIcon(icon)
        self.gridLayout_5 = QtGui.QGridLayout(NewRecordWindow)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox = QtGui.QGroupBox(NewRecordWindow)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 360))
        self.groupBox.setTitle(i18n("Kişisel Bilgiler"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setHorizontalSpacing(20)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setText(i18n("Ad:"))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 2)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_2.addWidget(self.lineEdit_4, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setText(i18n("Soyad:"))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 2)
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_2.addWidget(self.lineEdit_6, 1, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setText(i18n("Doğum Yeri:"))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 2, 0, 1, 2)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_2.addWidget(self.lineEdit_8, 2, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setText(i18n("Doğum Tarihi:"))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 3, 0, 1, 2)
        self.dateEdit_3 = QtGui.QDateEdit(self.groupBox)
        self.dateEdit_3.setObjectName(_fromUtf8("dateEdit_3"))
        self.gridLayout_2.addWidget(self.dateEdit_3, 3, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setText(i18n("Cinsiyet:"))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 4, 0, 1, 2)
        self.comboBox_6 = QtGui.QComboBox(self.groupBox)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.setItemText(0, i18n("Seçiniz..."))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.setItemText(1, i18n("Erkek"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.setItemText(2, i18n("Kadın"))
        self.gridLayout_2.addWidget(self.comboBox_6, 4, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setText(i18n("Medeni Durum:"))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 5, 0, 1, 2)
        self.comboBox_7 = QtGui.QComboBox(self.groupBox)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.setItemText(0, i18n("Seçiniz..."))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.setItemText(1, i18n("Evli"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.setItemText(2, i18n("Bekar"))
        self.gridLayout_2.addWidget(self.comboBox_7, 5, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setText(i18n("Meslek:"))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 6, 0, 1, 2)
        self.comboBox_8 = QtGui.QComboBox(self.groupBox)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.setItemText(0, i18n("Serbest Meslek"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.setItemText(1, i18n("Mühendis"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.setItemText(2, i18n("Doktor"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.setItemText(3, i18n("Öğretim Görevlisi"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.setItemText(4, i18n("Öğrenci"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.setItemText(5, i18n("Diğer"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.setItemText(6, i18n("Çalışmıyor"))
        self.gridLayout_2.addWidget(self.comboBox_8, 6, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setText(i18n("SGK No:"))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 7, 0, 1, 2)
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_2.addWidget(self.lineEdit_9, 7, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setText(i18n("İçki Kullanımı:"))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 8, 0, 1, 2)
        self.comboBox_9 = QtGui.QComboBox(self.groupBox)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.setItemText(0, i18n("Kullanmıyor"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.setItemText(1, i18n("Sosyal İçici"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.setItemText(2, i18n("1 Kadeh/Gün"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.setItemText(3, i18n("> 1 Kadeh/Gün"))
        self.gridLayout_2.addWidget(self.comboBox_9, 8, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setText(i18n("Sigara Kullanımı:"))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 9, 0, 1, 2)
        self.comboBox_10 = QtGui.QComboBox(self.groupBox)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.setItemText(0, i18n("Kullanmıyor"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.setItemText(1, i18n("Sosyal İçici"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.setItemText(2, i18n("Günde < 5"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.setItemText(3, i18n("0.5 Paket/Gün"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.setItemText(4, i18n("1 Paket/Gün"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.setItemText(5, i18n("1.5 Paket/Gün"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.setItemText(6, i18n("2 Paket/Gün"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.setItemText(7, i18n("> 2 Paket/Gün"))
        self.gridLayout_2.addWidget(self.comboBox_10, 9, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setText(i18n("Adres:"))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.groupBox)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 0, 1, 1, 2)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setText(i18n("Telefon:"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setText(i18n("E-Posta:"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/meeting-organizer.png")))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setText(i18n("Fotoğraf Ekle"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/list-resource-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 4)
        self.tabWidget = QtGui.QTabWidget(NewRecordWindow)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabDiseases = QtGui.QWidget()
        self.tabDiseases.setObjectName(_fromUtf8("tabDiseases"))
        self.tabWidget.addTab(self.tabDiseases, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 2, 0, 1, 4)
        self.label_14 = QtGui.QLabel(NewRecordWindow)
        self.label_14.setText(i18n("İlk Vizit Tarihi:"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 3, 0, 1, 1)
        self.label = QtGui.QLabel(NewRecordWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText(i18n("21.11.2011"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(414, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 3, 2, 1, 1)
        self.buttonBox_2 = QtGui.QDialogButtonBox(NewRecordWindow)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.gridLayout_5.addWidget(self.buttonBox_2, 3, 3, 1, 1)

        self.retranslateUi(NewRecordWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NewRecordWindow)

    def retranslateUi(self, NewRecordWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiseases), i18n("Hastalıklar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), i18n("Tetkikler"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), i18n("Sayfa"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), i18n("Sayfa"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), i18n("Sayfa"))

import icons_rc
import icons_rc
